#include <iostream>
using namespace std;
int v[1000];
int main()
{
    int n,m,a,b,i,sum=0,j=1;
    string s1,s2,s3,s4,s5,s6,s7,s8,s9,s10;
    cin>>n;
    while(n)
    {
        cin>>s1;
        if(s6[0]=='X')
            sum++;
        if(s6[9]=='X')
            sum++;
        if(s6[1]=='X')
            sum++;
        if(s6[8]=='X')
            sum++;
        if(s6[2]=='X')
            sum++;
        if(s6[7]=='X')
            sum++;
        if(s6[3]=='X')
            sum++;
        if(s6[6]=='X')
            sum++;
        if(s6[4]=='X')
            sum++;
        if(s6[5]=='X')
            sum++;
        cin>>s2;
        if(s6[0]=='X')
            sum++;
        if(s6[9]=='X')
            sum++;
        if(s6[1]=='X')
            sum+=2;
        if(s6[8]=='X')
            sum+=2;
        if(s6[2]=='X')
            sum+=2;
        if(s6[7]=='X')
            sum+=2;
        if(s6[3]=='X')
            sum+=2;
        if(s6[6]=='X')
            sum+=2;
        if(s6[4]=='X')
            sum+=2;
        if(s6[5]=='X')
            sum+=2;
        cin>>s3;
        if(s6[0]=='X')
            sum++;
        if(s6[9]=='X')
            sum++;
        if(s6[1]=='X')
            sum+=2;
        if(s6[8]=='X')
            sum+=2;
        if(s6[2]=='X')
            sum+=3;
        if(s6[7]=='X')
            sum+=3;
        if(s6[3]=='X')
            sum+=3;
        if(s6[6]=='X')
            sum+=3;
        if(s6[4]=='X')
            sum+=3;
        if(s6[5]=='X')
            sum+=3;
        cin>>s4;
        if(s6[0]=='X')
            sum++;
        if(s6[9]=='X')
            sum++;
        if(s6[1]=='X')
            sum+=2;
        if(s6[8]=='X')
            sum+=2;
        if(s6[2]=='X')
            sum+=3;
        if(s6[7]=='X')
            sum+=3;
        if(s6[3]=='X')
            sum+=4;
        if(s6[6]=='X')
            sum+=4;
        if(s6[4]=='X')
            sum+=4;
        if(s6[5]=='X')
            sum+=4;
        cin>>s5;
        if(s5[0]=='X')
            sum++;
        if(s5[9]=='X')
            sum++;
        if(s5[1]=='X')
            sum+=2;
        if(s5[8]=='X')
            sum+=2;
        if(s5[2]=='X')
            sum+=3;
        if(s5[7]=='X')
            sum+=3;
        if(s5[3]=='X')
            sum+=4;
        if(s5[6]=='X')
            sum+=4;
        if(s5[4]=='X')
            sum+=5;
        if(s5[5]=='X')
            sum+=5;
        cin>>s6;
        if(s6[0]=='X')
            sum++;
        if(s6[9]=='X')
            sum++;
        if(s6[1]=='X')
            sum+=2;
        if(s6[8]=='X')
            sum+=2;
        if(s6[2]=='X')
            sum+=3;
        if(s6[7]=='X')
            sum+=3;
        if(s6[3]=='X')
            sum+=4;
        if(s6[6]=='X')
            sum+=4;
        if(s6[4]=='X')
            sum+=5;
        if(s6[5]=='X')
            sum+=5;
        cin>>s7;
        if(s6[0]=='X')
            sum++;
        if(s6[9]=='X')
            sum++;
        if(s6[1]=='X')
            sum+=2;
        if(s6[8]=='X')
            sum+=2;
        if(s6[2]=='X')
            sum+=3;
        if(s6[7]=='X')
            sum+=3;
        if(s6[3]=='X')
            sum+=4;
        if(s6[6]=='X')
            sum+=4;
        if(s6[4]=='X')
            sum+=4;
        if(s6[5]=='X')
            sum+=4;
        cin>>s8;
        if(s6[0]=='X')
            sum++;
        if(s6[9]=='X')
            sum++;
        if(s6[1]=='X')
            sum+=2;
        if(s6[8]=='X')
            sum+=2;
        if(s6[2]=='X')
            sum+=3;
        if(s6[7]=='X')
            sum+=3;
        if(s6[3]=='X')
            sum+=3;
        if(s6[6]=='X')
            sum+=3;
        if(s6[4]=='X')
            sum+=3;
        if(s6[5]=='X')
            sum+=3;
        cin>>s9;
        if(s6[0]=='X')
            sum++;
        if(s6[9]=='X')
            sum++;
        if(s6[1]=='X')
            sum+=2;
        if(s6[8]=='X')
            sum+=2;
        if(s6[2]=='X')
            sum+=2;
        if(s6[7]=='X')
            sum+=2;
        if(s6[3]=='X')
            sum+=2;
        if(s6[6]=='X')
            sum+=2;
        if(s6[4]=='X')
            sum+=2;
        if(s6[5]=='X')
            sum+=2;
        cin>>s10;
        if(s6[0]=='X')
            sum++;
        if(s6[9]=='X')
            sum++;
        if(s6[1]=='X')
            sum++;
        if(s6[8]=='X')
            sum++;
        if(s6[2]=='X')
            sum++;
        if(s6[7]=='X')
            sum++;
        if(s6[3]=='X')
            sum++;
        if(s6[6]=='X')
            sum++;
        if(s6[4]=='X')
            sum++;
        if(s6[5]=='X')
            sum++;
        v[j]=sum;
        j++;
        sum=0;
        n--;
    }
    for(int jj=1;jj<=j;jj++)
        cout<<v[jj]<<'\n';
    return 0;
}
